### ISSUE TITLE
Top 5 pages

### ISSUE THREAD

**Issue by h-Benitez13** [vs0018/Project-One#11]
As a user, I want my likes to be stored in a different page from the vacation options.

**Tasks** 
- [x] using bootsrap, create a nav bar for the "top 5 pages" and "personal profile" 
- [x] create icons for profile and liked vacation spots
- [x] icons be clickable

**Comment by vs0018** [comment]
Completed by Whitman
