### ISSUE TITLE
API from console to array

### ISSUE THREAD

**Issue by h-Benitez13** [vs0018/Project-One#15]
As a user, I want the site/app I'm using to be fully functional, with correct information 

**Task**
- [ ]  pulled information from API stored in console
- [ ] within the ajax function, store variables
- [ ] stored variables to push towards an array: userLiked & userDislike
