### ISSUE TITLE
Profile grabber

### ISSUE THREAD

**Issue by h-Benitez13** [vs0018/Project-One#19]
As a user, I want to know I am in my profile

**Task**
- [ ] functions when read in synch., have modal display 
- [ ] in modal: forms- input (type= text) for first/last name, age, location [address], favorite hobbies
- [ ] in modal: forms- button (link) option for adding personal photo
- [ ] when the user enters text values in the input box: grabs value and pushes towards the profile page array
- [ ] photo-option: when clicked, gives the user the option to upload a photo
- [ ] submit at the bottom: button type= submit
- [ ] when button is clicked, remove modal, push first name towards the nav bar displaying "Hello, " + username
- [ ] user-info from modal, display when user clicks on the profile icon in the nav bar
