### ISSUE TITLE
Profile Image Upload 

### ISSUE THREAD

**Issue by cesarmarroquin22** [vs0018/Project-One#21]
As a user, I want to be able to upload an image in my profile page of myself and have the ability to crop it to fit it as I want. 

** Task ** 
- [ ] First of all, we will include all necessary library files and JavaScript in head. 
- [ ] Now in our HTML we will be able to display a 'Change Profile Picture' button and image preview section to display saved profile picture.
- [ ] Now we will create model box in our HTML for image upload and crop functionality.
- [ ] Now will show the model box using JQuery when click on Change Profile Picture button. 
- [ ] Now we will handle the image crop and call saveCropImage() ajax method to save image. 
- [ ] Using a JavaScript function to save the current image and then upload it.
